USE customer_db;
SELECT * FROM customer;

-- What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue
from customer
group by gender ;

-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount 
from customer 
where discount_applied ='Yes' and purchase_amount>= (select avg(purchase_amount ) from customer);

-- Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating),2) as rating
from customer 
group by item_purchased 
order by rating desc
limit 5;

-- Compare the average purchase amounts between Standard and Express shipping.
	select  shipping_type  ,avg(purchase_amount)as avg_price 
	from customer
	where shipping_type = 'Express' or shipping_type='Standard'
    group by shipping_type;
    
-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customer, avg(purchase_amount) as avg_price , sum(purchase_amount) as revenue 
from customer
group by subscription_status
order by revenue , avg_price;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased ,
sum(case when  discount_applied ='yes' then 1
else 0 end)*100 / count(*) as discount_rate 
from customer 
group by item_purchased
order by discount_rate desc 
limit 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id , previous_purchases ,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as segment 
from customer
)
select segment , count(*) as 'Nnmber of Customers' from customer_type 
group by segment; 
    
-- What are the top 3 most purchased products within each category?
with item_counts as (
select category,  item_purchased  ,
count(customer_id) as total_orders ,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased 
)
select total_orders , item_rank ,category, item_purchased 
from item_counts
where item_rank<=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select  subscription_status ,count(customer_id) as customer_count 	
from customer
where previous_purchases > 5
group by subscription_status ;

-- What is the revenue contribution of each age group?
select age_group , sum(purchase_amount) as totalrevenue
from customer
group by age_group
order by totalrevenue desc;
